"""Configuration module for Gestio Financial Management."""

from .paths import (
    DATA_DIR, DB_PATH, TO_SCAN_DIR, SORTED_DIR, PROBLEMATIC_DIR,
    REVENUS_A_TRAITER, REVENUS_TRAITES,
    OCR_LOGS_DIR, LOG_PATH, OCR_PERFORMANCE_LOG, PATTERN_STATS_LOG, OCR_SCAN_LOG,
    POTENTIAL_PATTERNS_LOG, CSV_EXPORT_DIR, CSV_TRANSACTIONS_SANS_TICKETS
)

from .ocr_config import (
    UBER_TAX_RATE,
    UBER_NET_MULTIPLIER,
    UBER_KEYWORDS,
    OCR_SUCCESS_THRESHOLD,
    OCR_DETECTION_MINIMUM,
    SUCCESS_LEVELS
)
from .ui_config import (
    PRIMARY_COLOR,
    SECONDARY_COLOR,
    DANGER_COLOR,
    WARNING_COLOR,
    BACKGROUND_LIGHT,
    TEXT_PRIMARY,
    TEXT_SECONDARY,
    BORDER_RADIUS,
    BOX_SHADOW
)

__all__ = [
    # Paths
    'DATA_DIR', 'DB_PATH', 'TO_SCAN_DIR', 'SORTED_DIR', 'PROBLEMATIC_DIR',
    'REVENUS_A_TRAITER', 'REVENUS_TRAITES',
    'OCR_LOGS_DIR', 'LOG_PATH', 'OCR_PERFORMANCE_LOG', 'PATTERN_STATS_LOG', 'OCR_SCAN_LOG',
    'POTENTIAL_PATTERNS_LOG', 'CSV_EXPORT_DIR', 'CSV_TRANSACTIONS_SANS_TICKETS',

    # OCR Config
    'UBER_TAX_RATE', 'UBER_NET_MULTIPLIER', 'UBER_KEYWORDS',
    'OCR_SUCCESS_THRESHOLD', 'OCR_DETECTION_MINIMUM', 'SUCCESS_LEVELS',

    # UI Config
    'PRIMARY_COLOR', 'SECONDARY_COLOR', 'DANGER_COLOR', 'WARNING_COLOR',
    'BACKGROUND_LIGHT', 'TEXT_PRIMARY', 'TEXT_SECONDARY',
    'BORDER_RADIUS', 'BOX_SHADOW'
]
