name: 🚀 Build & Release Gestion Financière Little

permissions:
  contents: write
  actions: read

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build et Release multi-plateforme
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: 🧰 Checkout du code
        uses: actions/checkout@v4

      - name: 📝 Créer le guide d'installation
        run: |
          # Méthode compatible Windows/Linux/macOS
          $content = @"
          # 📖 Guide d'Installation - Gestion Financière Little

          ## 🚀 Premier Lancement

          1. **Extraire** le fichier ZIP téléchargé
          2. **Lancer** `GestionFinanciereLittle.exe` (Windows) ou `GestionFinanciereLittle` (Linux/macOS)
          3. **Le guide s'ouvrira automatiquement** la première fois
          4. **Conserver** tous les fichiers dans le même dossier

          ## ⚙️ Configuration Requise

          - **Windows 10/11**, **Linux** (Ubuntu 18.04+), **macOS** (10.15+)
          - 4 GB RAM minimum
          - Connexion internet pour les mises à jour

          ## 🔧 Dépannage

          ### L'application ne se lance pas
          - Vérifier que tous les fichiers sont dans le même dossier
          - Redémarrer l'ordinateur
          - Exécuter en mode administrateur (Windows)

          ### Le guide ne s'ouvre pas
          - Le fichier `GUIDE_INSTALLATION.md` doit être présent
          - Vérifier les permissions de lecture

          ## 📞 Support

          En cas de problème, consulter le repository GitHub.

          *Ce guide s'ouvre automatiquement au premier lancement et restera accessible.*
          "@
          Out-File -FilePath "GUIDE_INSTALLATION.md" -InputObject $content -Encoding UTF8
        shell: pwsh

      - name: 🐍 Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # ... [le reste de votre configuration Tesseract reste identique] ...

      - name: 🏗️ Compiler l'application (optimisé antivirus)
        run: |
          # Créer un fichier .spec optimisé
          cat > gestiolittle.spec << 'EOF'
          # -*- mode: python ; coding: utf-8 -*-
          import os
          import glob
          
          block_cipher = None
          
          # Collecter tous les fichiers .py SAUF lancer_gestiolittle.py
          py_files = [f for f in glob.glob('*.py') if f != 'lancer_gestiolittle.py']
          datas_list = [(f, '.') for f in py_files]
          
          # Ajouter le guide d'installation
          datas_list.append(('GUIDE_INSTALLATION.md', '.'))
          
          # Ajouter le dossier tesseract s'il existe
          if os.path.exists('tesseract'):
              datas_list.append(('tesseract', 'tesseract'))
          
          a = Analysis(
              ['lancer_gestiolittle.py'],
              pathex=[],
              binaries=[],
              datas=datas_list,
              hiddenimports=['streamlit'],
              hookspath=[],
              hooksconfig={},
              runtime_hooks=[],
              excludes=['pytest', 'unittest', 'test', '_pytest', 'setuptools', 'pip', 'wheel'],
              win_no_prefer_redirects=False,
              win_private_assemblies=False,
              cipher=block_cipher,
              noarchive=False,
          )
          
          pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
          
          exe = EXE(
              pyz,
              a.scripts,
              a.binaries,
              a.zipfiles,
              a.datas,
              [],
              name='GestionFinanciereLittle',
              debug=False,
              bootloader_ignore_signals=False,
              strip=False,
              upx=False,
              console=True,
              disable_windowed_traceback=False,
              argv_emulation=False,
              target_arch=None,
              codesign_identity=None,
              entitlements_file=None,
          )
          EOF
          
          # Compiler avec le .spec optimisé
          pyinstaller gestiolittle.spec --clean --noconfirm
          
          # Copier gestiolittle.py et tesseract à côté de l'exécutable
          cp gestiolittle.py dist/
          cp GUIDE_INSTALLATION.md dist/
          if [ -d "tesseract" ]; then
            cp -r tesseract dist/
          fi
        shell: bash

      - name: 📦 Créer le package de distribution
        run: |
          cd dist
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            7z a -tzip GestionFinanciereLittle-Windows.zip GestionFinanciereLittle.exe gestiolittle.py GUIDE_INSTALLATION.md tesseract/
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            zip -r GestionFinanciereLittle-Linux.zip GestionFinanciereLittle gestiolittle.py GUIDE_INSTALLATION.md tesseract/
          else
            zip -r GestionFinanciereLittle-macOS.zip GestionFinanciereLittle gestiolittle.py GUIDE_INSTALLATION.md tesseract/
          fi
          cd ..
        shell: bash

      - name: 📤 Upload de l'exécutable pour la Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "Gestion Financière Little v${{ github.run_number }}"
          body: |
            🚀 Nouvelle version générée automatiquement.

            ✅ Compatible Windows, Linux et macOS.
            📖 **Guide d'installation inclus** - s'ouvre automatiquement au premier lancement.
            
            ## 📦 Installation
            1. Télécharger le ZIP correspondant à votre OS
            2. Extraire dans un dossier
            3. Lancer l'exécutable
            4. Le guide s'ouvrira automatiquement

            ⚠️ **Important** : Tous les fichiers doivent rester dans le même dossier !
          files: |
            dist/GestionFinanciereLittle*.zip
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
