name: 🚀 Build & Release Gestion Financière Little
permissions:
  contents: write  # ✅ autorise la création de releases et de tags
  actions: read


on:
  push:
    branches: [ main ]
  workflow_dispatch: # Permet de le lancer manuellement depuis GitHub

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: 🧩 Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: ⚙️ Build executable
        run: |
          pyinstaller --onefile lancer_gestiolittle.py
        shell: bash

      - name: 📤 Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: dist/*

  release:
    name: ✨ Create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 📥 Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: builds

      - name: 🧰 Display downloaded files
        run: ls -R builds

      - name: 🏷️ Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "Gestion Financière Little v${{ github.run_number }}"
          body: |
            🚀 Nouvelle version automatique compilée depuis GitHub Actions !
            Contient :
            - 🪟 Windows (.exe)
            - 🐧 Linux (.AppImage)
            - 🍎 macOS (.dmg)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📎 Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          files: builds/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
