name: 🚀 Build & Release Gestion Financière Little

permissions:
  contents: write
  actions: read

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build et Release multi-plateforme
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: 🧰 Checkout du code
        uses: actions/checkout@v4

      - name: 🐍 Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: 📥 Installer Tesseract OCR
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            # Télécharger et installer Tesseract pour Windows
            choco install tesseract -y
            # Créer le dossier tesseract local
            mkdir -p tesseract
            # Copier Tesseract depuis l'installation système
            cp -r "C:/Program Files/Tesseract-OCR/"* tesseract/ || true
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y tesseract-ocr tesseract-ocr-fra
            mkdir -p tesseract
            cp /usr/bin/tesseract tesseract/ || true
            cp -r /usr/share/tesseract-ocr tesseract/tessdata || true
          else
            brew install tesseract
            mkdir -p tesseract
            cp /usr/local/bin/tesseract tesseract/ || true
            cp -r /usr/local/share/tessdata tesseract/ || true
          fi
        shell: bash
      
      - name: 📝 Créer script de lancement pour Linux/macOS
        if: runner.os != 'Windows'
        run: |
          cat > dist/run.sh << 'RUNSCRIPT'
          #!/bin/bash
          # Script de lancement Gestion Financière Little
          
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "  🚀 Gestion Financière Little"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo ""
          
          # Détection spécifique de MX Linux et dérivés Debian
          detect_linux_distro() {
              if [ -f /etc/os-release ]; then
                  . /etc/os-release
                  echo "$NAME"
              elif command -v lsb_release &> /dev/null; then
                  lsb_release -d | cut -f2
              else
                  echo "Unknown"
              fi
          }
          
          DISTRO=$(detect_linux_distro)
          echo "🐧 Distribution détectée: $DISTRO"
          echo ""
          
          # Fonction pour trouver streamlit
          find_streamlit() {
              # Chercher streamlit dans les chemins communs
              local paths=(
                  "$HOME/.local/bin/streamlit"
                  "/usr/local/bin/streamlit" 
                  "/usr/bin/streamlit"
                  "$(which streamlit 2>/dev/null)"
                  "$(command -v streamlit 2>/dev/null)"
              )
              
              for path in "${paths[@]}"; do
                  if [ -f "$path" ] || [ -x "$path" ]; then
                      echo "$path"
                      return 0
                  fi
              done
              return 1
          }
          
          # Vérifier Python
          if ! command -v python3 &> /dev/null; then
              echo "⚠️  Python 3 n'est pas installé sur votre système."
              echo ""
              read -p "❓ Voulez-vous que je l'installe automatiquement ? (o/N) " response
              
              if [[ "$response" =~ ^[OoYy]$ ]]; then
                  case "$DISTRO" in
                      *"Debian"*|*"Ubuntu"*|*"MX"*|*"Linux Mint"*)
                          sudo apt-get update || {
                              echo "❌ Échec de la mise à jour des paquets"
                              exit 1
                          }
                          sudo apt-get install -y python3 python3-pip python3-venv python3-full pipx || {
                              echo "❌ Échec de l'installation automatique."
                              echo "📋 Essayez manuellement : sudo apt install python3 python3-pip python3-venv"
                              exit 1
                          }
                          ;;
                      *"Fedora"*|*"Red Hat"*|*"CentOS"*)
                          sudo dnf install -y python3 python3-pip python3-virtualenv pipx || {
                              echo "❌ Échec de l'installation automatique."
                              echo "📋 Essayez manuellement : sudo dnf install python3 python3-pip"
                              exit 1
                          }
                          ;;
                      *"Arch"*|*"Manjaro"*)
                          sudo pacman -S --noconfirm python python-pip python-virtualenv pipx || {
                              echo "❌ Échec de l'installation automatique."
                              echo "📋 Essayez manuellement : sudo pacman -S python python-pip"
                              exit 1
                          }
                          ;;
                      *"macOS"*|*"Darwin"*)
                          brew install python@3.11 pipx || {
                              echo "❌ Échec de l'installation automatique."
                              echo "📋 Essayez manuellement : brew install python@3.11"
                              exit 1
                          }
                          ;;
                      *)
                          echo "❌ Distribution non supportée pour l'installation automatique."
                          echo "📋 Installez Python manuellement pour votre distribution."
                          exit 1
                          ;;
                  esac
                  echo "✅ Python installé avec succès !"
              else
                  echo ""
                  echo "📋 Installez Python manuellement, puis relancez ce script."
                  exit 1
              fi
          fi
          
          echo "✅ Python détecté: $(python3 --version)"
          echo ""
          
          # Vérifier si pipx est installé et configuré
          if command -v pipx &> /dev/null; then
              echo "🔧 pipx détecté, vérification du PATH..."
              # Vérifier si le PATH inclut ~/.local/bin
              if [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
                  echo "📝 Mise à jour du PATH pour pipx..."
                  pipx ensurepath
                  echo "💡 Fermez et rouvrez le terminal, ou exécutez :"
                  echo "   source ~/.bashrc"
                  export PATH="$HOME/.local/bin:$PATH"
              fi
          fi
          
          # Solution pour MX Linux/Debian : utiliser pipx ou venv
          VENV_DIR=".venv"
          USE_PIPX=false
          
          # D'abord vérifier si streamlit est déjà disponible
          STREAMLIT_PATH=$(find_streamlit)
          if [ -n "$STREAMLIT_PATH" ]; then
              echo "✅ Streamlit trouvé : $STREAMLIT_PATH"
              echo "🎯 Utilisation de Streamlit existant"
          else
              echo "🔍 Streamlit non trouvé, installation..."
              
              # Demander la méthode d'installation
              echo ""
              echo "📦 Choisissez la méthode d'installation :"
              echo "   1) Environnement virtuel (recommandé)"
              echo "   2) pipx (installation globale)"
              read -p "   Votre choix [1/2] : " install_choice
              
              if [ "$install_choice" = "2" ]; then
                  USE_PIPX=true
              fi
              
              if [ "$USE_PIPX" = true ]; then
                  # Méthode pipx
                  if ! command -v pipx &> /dev/null; then
                      echo "📦 Installation de pipx..."
                      case "$DISTRO" in
                          *"Debian"*|*"Ubuntu"*|*"MX"*|*"Linux Mint"*)
                              sudo apt-get install -y pipx || {
                                  echo "❌ Impossible d'installer pipx"
                                  exit 1
                              }
                              ;;
                          *"Fedora"*|*"Red Hat"*|*"CentOS"*)
                              sudo dnf install -y pipx || {
                                  echo "❌ Impossible d'installer pipx"
                                  exit 1
                              }
                              ;;
                          *"Arch"*|*"Manjaro"*)
                              sudo pacman -S --noconfirm pipx || {
                                  echo "❌ Impossible d'installer pipx"
                                  exit 1
                              }
                              ;;
                          *"macOS"*|*"Darwin"*)
                              brew install pipx || {
                                  echo "❌ Impossible d'installer pipx"
                                  exit 1
                              }
                              ;;
                      esac
                  fi
                  
                  echo "📦 Installation avec pipx..."
                  pipx ensurepath
                  export PATH="$HOME/.local/bin:$PATH"
                  pipx install streamlit pillow pytesseract pandas matplotlib || {
                      echo "❌ Erreur lors de l'installation avec pipx"
                      exit 1
                  }
                  echo "✅ Streamlit installé avec pipx !"
              else
                  # Méthode environnement virtuel
                  if [ ! -d "$VENV_DIR" ]; then
                      echo "📦 Création de l'environnement virtuel Python..."
                      
                      # Vérifier si python3-venv est installé
                      if ! python3 -c "import venv" 2>/dev/null; then
                          echo "⚠️  Le module venv n'est pas disponible."
                          echo "📦 Installation de python3-venv..."
                          
                          case "$DISTRO" in
                              *"Debian"*|*"Ubuntu"*|*"MX"*|*"Linux Mint"*)
                                  sudo apt-get install -y python3-venv python3-full || {
                                      echo "❌ Impossible d'installer python3-venv"
                                      echo "🔁 Retour à la méthode pipx..."
                                      pipx install streamlit pillow pytesseract pandas matplotlib
                                      pipx ensurepath
                                      export PATH="$HOME/.local/bin:$PATH"
                                      USE_PIPX=true
                                  }
                                  ;;
                              *"Fedora"*|*"Red Hat"*|*"CentOS"*)
                                  sudo dnf install -y python3-virtualenv || {
                                      echo "❌ Impossible d'installer python3-virtualenv"
                                      exit 1
                                  }
                                  ;;
                              *"Arch"*|*"Manjaro"*)
                                  sudo pacman -S --noconfirm python-virtualenv || {
                                      echo "❌ Impossible d'installer python-virtualenv"
                                      exit 1
                                  }
                                  ;;
                          esac
                      fi
                      
                      if [ "$USE_PIPX" != true ]; then
                          python3 -m venv "$VENV_DIR" || {
                              echo "❌ Impossible de créer l'environnement virtuel"
                              exit 1
                          }
                          echo "✅ Environnement virtuel créé !"
                      fi
                  fi
                  
                  if [ "$USE_PIPX" != true ]; then
                      # Activer l'environnement virtuel
                      source "$VENV_DIR/bin/activate"
                      echo "✅ Environnement virtuel activé"
                      
                      # Installer dans le venv
                      python -m pip install --upgrade pip --quiet
                      python -m pip install streamlit pillow pytesseract pandas matplotlib --quiet || {
                          echo "❌ Erreur lors de l'installation des dépendances"
                          exit 1
                      }
                      echo "✅ Streamlit installé dans l'environnement virtuel !"
                  fi
              fi
          fi
          
          # Vérifier Tesseract OCR
          if ! command -v tesseract &> /dev/null; then
              echo "⚠️  Tesseract OCR n'est pas installé (optionnel pour OCR)."
              echo "   Pour l'installer :"
              case "$DISTRO" in
                  *"Debian"*|*"Ubuntu"*|*"MX"*|*"Linux Mint"*)
                      echo "   sudo apt install tesseract-ocr tesseract-ocr-fra"
                      ;;
                  *"Fedora"*|*"Red Hat"*|*"CentOS"*)
                      echo "   sudo dnf install tesseract tesseract-langpack-fra"
                      ;;
                  *"Arch"*|*"Manjaro"*)
                      echo "   sudo pacman -S tesseract tesseract-data-fra"
                      ;;
                  *"macOS"*|*"Darwin"*)
                      echo "   brew install tesseract tesseract-lang/fra"
                      ;;
              esac
              echo ""
          fi
          
          # Lancer l'application
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "  ▶️  Lancement de l'application..."
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo ""
          echo "💡 L'application va s'ouvrir dans votre navigateur"
          echo "💡 Pour arrêter : Fermez ce terminal (Ctrl+C)"
          echo ""
          
          sleep 2
          
          # Déterminer comment lancer streamlit
          if [ "$USE_PIPX" = true ] || [ -n "$STREAMLIT_PATH" ]; then
              streamlit run gestiolittle.py --server.port 8501
          else
              python -m streamlit run gestiolittle.py --server.port 8501
          fi
          RUNSCRIPT
          
          chmod +x dist/run.sh
        shell: bash

      - name: 🏗️ Compiler l'application (optimisé antivirus)
        run: |
          # Créer un fichier .spec optimisé
          cat > gestiolittle.spec << 'EOF'
          # -*- mode: python ; coding: utf-8 -*-
          import os
          import glob
          
          block_cipher = None
          
          # Collecter tous les fichiers .py SAUF lancer_gestiolittle.py
          py_files = [f for f in glob.glob('*.py') if f != 'lancer_gestiolittle.py']
          datas_list = [(f, '.') for f in py_files]
          
          # Ajouter le dossier tesseract s'il existe
          if os.path.exists('tesseract'):
              datas_list.append(('tesseract', 'tesseract'))
          
          a = Analysis(
              ['lancer_gestiolittle.py'],
              pathex=[],
              binaries=[],
              datas=datas_list,
              hiddenimports=['streamlit'],
              hookspath=[],
              hooksconfig={},
              runtime_hooks=[],
              excludes=['pytest', 'unittest', 'test', '_pytest', 'setuptools', 'pip', 'wheel'],
              win_no_prefer_redirects=False,
              win_private_assemblies=False,
              cipher=block_cipher,
              noarchive=False,
          )
          
          pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
          
          exe = EXE(
              pyz,
              a.scripts,
              a.binaries,
              a.zipfiles,
              a.datas,
              [],
              name='GestionFinanciereLittle',
              debug=False,
              bootloader_ignore_signals=False,
              strip=False,
              upx=False,
              console=True,
              disable_windowed_traceback=False,
              argv_emulation=False,
              target_arch=None,
              codesign_identity=None,
              entitlements_file=None,
          )
          EOF
          
          # Compiler avec le .spec optimisé
          pyinstaller gestiolittle.spec --clean --noconfirm
          
          # Copier gestiolittle.py et tesseract à côté de l'exécutable
          cp gestiolittle.py dist/
          if [ -d "tesseract" ]; then
            cp -r tesseract dist/
          fi
        shell: bash

      - name: 📦 Créer le package de distribution
        run: |
          cd dist
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            7z a -tzip GestionFinanciereLittle-Windows.zip GestionFinanciereLittle.exe gestiolittle.py tesseract/
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            # Pour Linux : distribution du code source + script de lancement
            zip -r GestionFinanciereLittle-Linux.zip gestiolittle.py run.sh tesseract/
          else
            # Pour macOS : distribution du code source + script de lancement
            zip -r GestionFinanciereLittle-macOS.zip gestiolittle.py run.sh tesseract/
          fi
          cd ..
        shell: bash

      - name: 📤 Upload de l'exécutable pour la Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "Gestion Financière Little v${{ github.run_number }}"
          body: |
            🚀 Nouvelle version générée automatiquement.

            ## 📦 Téléchargements par Plateforme
            
            ### 🪟 Windows (Exécutable Standalone)
            - `GestionFinanciereLittle-Windows.zip`
            - ✅ Aucune installation requise
            - ⚠️ Extraire le ZIP et lancer le .exe
            
            ### 🐧 Linux (Script Python)
            - `GestionFinanciereLittle-Linux.zip`
            - 📋 Prérequis : Python 3.11+
            - ▶️ Lancer : `chmod +x run.sh && ./run.sh`
            
            ### 🍎 macOS (Script Python)
            - `GestionFinanciereLittle-macOS.zip`
            - 📋 Prérequis : Python 3.11+
            - ▶️ Lancer : `chmod +x run.sh && ./run.sh`
            
            ---
            
            🔏 L'exécutable Windows est signé numériquement.
            
            📖 Voir le guide complet : [GUIDE_INSTALLATION.md](https://github.com/mdjabi2005-commits/gestion-financiere_little/blob/main/GUIDE_INSTALLATION.md)
          files: |
            dist/GestionFinanciereLittle*.zip
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
